MvcCorePaginacionRegistros/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCorePaginacionRegistros.Models;
using MvcCorePaginacionRegistros.Repositories;

namespace MvcCorePaginacionRegistros.Controllers
{
    public class EmpleadosController : Controller
    {
        private RepositoryEmpleados repo;
        private RepositoryHospital repoH;

        public EmpleadosController(RepositoryEmpleados repo, RepositoryHospital repoH)
        {
            this.repo = repo;
            this.repoH = repoH;
        }
        /*public IActionResult Index(int deptno, int? posicion)
        {
            List<Empleado> empleados = this.repo.FindEmpleados(deptno);
            return View(empleados);
        }*/

        public async Task<IActionResult> Index(int deptno, int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            int numregistros = this.repoH.GetNumeroRegistrosVistaEmpleadoDept(deptno);
            ViewData["REGISTROS"] = numregistros;
            ViewData["DEPTNO"] = deptno;
            List<Empleado> empleados = await this.repoH.GetEmpleadoAsync(deptno, posicion.Value);
            return View(empleados);
        }
    }
}

MvcCorePaginacionRegistros/Views/Shared/Components/MenuDepartamentos/Default.cshtml
@model List<Departamento>

<div class="dropdown">
    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
        Menú departamentos
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
        @foreach (Departamento dept in Model)
        {
            <li>
                <a class="dropdown-item" asp-controller="Empleados" asp-action="Index" asp-route-deptno="@dept.DeptNo">
                    @dept.Nombre
                </a>
            </li>
        }
    </ul>
</div>